export const QUERY_SET = 'QUERY_SET';
export const QUERY_SET_TYPE = 'QUERY_SET_TYPE';

export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS';
export const MOVIES_FETCH_FAILURE = 'MOVIES_FETCH_FAILURE';
export const MOVIES_SORT_CHANGE = 'MOVIES_SORT_CHANGE';

export const MOVIE_FETCH = 'MOVIE_FETCH';
export const MOVIE_FETCH_SUCCESS = 'MOVIE_FETCH_SUCCESS';
export const MOVIE_FETCH_FAILURE = 'MOVIE_FETCH_FAILURE';

export const DIRECTOR_INFO_FETCH = 'DIRECTOR_INFO_FETCH';
export const DIRECTOR_INFO_FETCH_SUCCESS = 'DIRECTOR_INFO_FETCH_SUCCESS';
export const DIRECTOR_INFO_FETCH_FAILURE = 'DIRECTOR_INFO_FETCH_FAILURE';
